version: '3.8'
services:
  gateway:
    build: ./gateway
    image: share_gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: share_server
    container_name: server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres