version: '3.8'
services:
  gateway:
    build: ./gateway
    image: share_gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: share_server
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
      - DB_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432

  db:
    image: postgres:13.7-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
#      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres